apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dpl
  namespace: default
  labels:
    app: app-depl
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app-depl
  template:
    metadata:
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        prometheus.io/path: '/metrics'
      labels:
        app: app-depl
    spec:
      serviceAccountName: default
      containers:
      - name: app-depl
        image: mobinesh/arvan:1.0
        #command: ["dotnet", "appApi.dll"]
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1G"
            cpu: "500m"
        securityContext:
            privileged: false
            allowPrivilegeEscalation: false
        env:
          - name: DB_ADDR
            valueFrom:
              secretKeyRef:
                name: app-sec
                key: DB_ADDR
        envFrom:
          - configMapRef:
              name: app-cm   
        livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
        readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
        volumeMounts:
        - name: pvc-mount
          mountPath: /storage
        ports:
          - containerPort: 80 
          - containerPort: 8090



