apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default
spec:
  selector:
    app: app-depl
  type: NodePort
  ports:
    - name: rest
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080