apiVersion: v1
kind: Service
metadata:
  name: blob-svc
  namespace: default
spec:
  selector:
    app: blob-depl
  type: ClusterIP
  ports:
    - name: rest
      protocol: TCP
      port: 80
      targetPort: 80
    - name: grpc
      protocol: TCP
      port: 5001
      targetPort: 5001